package float

import "fmt"

// Format converts the extended floating-point number f to a string,
// according to the format fmt. It rounds the result assuming that the
// original was obtained from a floating-point value of 80 bits.
//
// The format fmt is one of
// 'b' (-ddddp±ddd, a binary exponent),
// 'e' (-d.dddde±dd, a decimal exponent),
// 'E' (-d.ddddE±dd, a decimal exponent),
// 'f' (-ddd.dddd, no exponent),
// 'g' ('e' for large exponents, 'f' otherwise),
// 'G' ('E' for large exponents, 'f' otherwise).
//
// The precision prec controls the number of digits (excluding the exponent)
// printed by the 'e', 'E', 'f', 'g' and 'G' formats.
// For 'e', 'E', 'f' it is the number of digits after the decimal point.
// For 'g' and 'G' it is the maximum number of significant digits (trailing
// zeros are removed); a negative prec uses 21 digits, enough for any X80 value
// to round-trip.
func (a X80) Format(fmt byte, prec int) string {
	return string(a.genericFtoa(make([]byte, 0, max(prec+4, 24)), fmt, prec))
}

// Append appends the string form of the floating-point number f,
// as generated by FormatFloat, to dst and returns the extended buffer.
func (a X80) Append(dst []byte, fmt byte, prec int) []byte {
	return a.genericFtoa(dst, fmt, prec)
}

func (a X80) genericFtoa(dst []byte, fmt byte, prec int) []byte {
	a = a.canonical()
	neg := a.sign()
	exp := a.exp()
	mant := a.frac()

	switch exp {
	case 0x7fff:
		// Inf, NaN
		var s string
		switch {
		case mant<<1 != 0:
			s = "NaN"
		case neg:
			s = "-Inf"
		default:
			s = "+Inf"
		}
		return append(dst, s...)

	case 0:
		// denormalized
		exp++

	default:
		// add implicit top bit
		mant |= uint64(1) << 63
	}
	exp -= 0x3fff // -bias

	// Pick off easy binary, hex formats.
	if fmt == 'b' {
		return fmtB(dst, neg, mant, exp)
	}

	return bigFtoa(dst, prec, fmt, neg, mant, exp)
}

// decimalGuardDigits is the number of digits kept beyond those printed by the
// 'e' and 'g' formats. Up to ~270 shift passes each truncate the value by less
// than one unit in the last kept digit, which disturbs at most the last 3
// guard digits; the printed digits are rounded wrongly only if the exact
// digits following them are a run of more than 25 nines or zeros.
const decimalGuardDigits = 30

// bigFtoa uses multiprecision computations to format a float.
func bigFtoa(dst []byte, prec int, fmt byte, neg bool, mant uint64, exp int) []byte {
	d := new(decimal)
	// 'e' and 'g' only need the leading digits. Every shift pass truncates the
	// digits beyond the limit, so keep enough guard digits that the rounding
	// digits stay exact; 'f' needs all integer digits.
	switch fmt {
	case 'e', 'E':
		d.max = prec + 1 + decimalGuardDigits
	case 'g', 'G':
		d.max = max(prec, 21) + decimalGuardDigits
	}
	d.Assign(mant)
	d.Shift(exp - 63)
	var digs decimalSlice

	// Round appropriately.
	switch fmt {
	case 'e', 'E':
		d.Round(prec + 1)
	case 'f':
		d.Round(d.dp + prec)
	case 'g', 'G':
		if prec < 0 {
			prec = 21
		} else if prec == 0 {
			prec = 1
		}
		d.Round(prec)
	}
	digs = decimalSlice{d: d.d[:], nd: d.nd, dp: d.dp}

	return formatDigits(dst, neg, digs, prec, fmt)
}

func formatDigits(dst []byte, neg bool, digs decimalSlice, prec int, fmt byte) []byte {
	switch fmt {
	case 'e', 'E':
		return fmtE(dst, neg, digs, prec, fmt)
	case 'f':
		return fmtF(dst, neg, digs, prec)
	case 'g', 'G':
		eprec := prec
		if eprec > digs.nd && digs.nd >= digs.dp {
			eprec = digs.nd
		}
		// %e is used if the exponent from the conversion
		// is less than -4 or greater than or equal to the precision.
		exp := digs.dp - 1
		if exp < -4 || exp >= eprec {
			if prec > digs.nd {
				prec = digs.nd
			}
			return fmtE(dst, neg, digs, prec-1, fmt+'e'-'g')
		}
		if prec > digs.dp {
			prec = digs.nd
		}
		return fmtF(dst, neg, digs, max(prec-digs.dp, 0))
	}

	// unknown format
	return append(dst, '%', fmt)
}

type decimalSlice struct {
	d      []byte
	nd, dp int
}

// %e: -d.ddddde±dd
func fmtE(dst []byte, neg bool, d decimalSlice, prec int, fmt byte) []byte {
	// sign
	if neg {
		dst = append(dst, '-')
	}

	// first digit
	ch := byte('0')
	if d.nd != 0 {
		ch = d.d[0]
	}
	dst = append(dst, ch)

	// .moredigits
	if prec > 0 {
		dst = append(dst, '.')
		i := 1
		m := min(d.nd, prec+1)
		if i < m {
			dst = append(dst, d.d[i:m]...)
			i = m
		}
		for ; i <= prec; i++ {
			dst = append(dst, '0')
		}
	}

	// e±
	dst = append(dst, fmt)
	exp := d.dp - 1
	if d.nd == 0 { // special case: 0 has exponent 0
		exp = 0
	}
	if exp < 0 {
		ch = '-'
		exp = -exp
	} else {
		ch = '+'
	}
	dst = append(dst, ch)

	// dd, ddd or dddd
	switch {
	case exp < 10:
		dst = append(dst, '0', byte(exp)+'0')
	case exp < 100:
		dst = append(dst, byte(exp/10)+'0', byte(exp%10)+'0')
	case exp < 1000:
		dst = append(dst, byte(exp/100)+'0', byte(exp/10%10)+'0', byte(exp%10)+'0')
	default:
		dst = append(dst, byte(exp/1000)+'0', byte(exp/100%10)+'0', byte(exp/10%10)+'0', byte(exp%10)+'0')
	}

	return dst
}

// %f: -ddddddd.ddddd
func fmtF(dst []byte, neg bool, d decimalSlice, prec int) []byte {
	// sign
	if neg {
		dst = append(dst, '-')
	}

	// integer, padded with zeros as needed.
	if d.dp > 0 {
		m := min(d.nd, d.dp)
		dst = append(dst, d.d[:m]...)
		for ; m < d.dp; m++ {
			dst = append(dst, '0')
		}
	} else {
		dst = append(dst, '0')
	}

	// fraction
	if prec > 0 {
		dst = append(dst, '.')
		for i := range prec {
			ch := byte('0')
			if j := d.dp + i; 0 <= j && j < d.nd {
				ch = d.d[j]
			}
			dst = append(dst, ch)
		}
	}

	return dst
}

// %b: -ddddddddp±ddd
func fmtB(dst []byte, neg bool, mant uint64, exp int) []byte {
	// sign
	if neg {
		dst = append(dst, '-')
	}

	// mantissa
	dst, _ = formatBits(dst, mant, 10, false, true)

	// p
	dst = append(dst, 'p')

	// ±exponent
	exp -= 63
	if exp >= 0 {
		dst = append(dst, '+')
	}
	dst, _ = formatBits(dst, uint64(exp), 10, exp < 0, true)

	return dst
}

// Internal returns the internal represantion of the 80bit float value in hex format.
func (a X80) Internal() string {
	return fmt.Sprintf("%04X%016X", a.high, a.low)
}

// String formats a with the 'g' verb and enough digits to round-trip.
func (a X80) String() string {
	return a.Format('g', -1)
}
