// Command gentables writes trig_tables.go, the bits of 2/pi used for the
// argument reduction of the trigonometric functions.
//
// Run it with go generate in the package directory.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"math/big"
	"os"
)

// words is enough for the largest X80 exponent: the reduction uses words
// up to index (16320-2)/64 + 5 = 259.
const words = 264

// atanInv returns atan(1/x) * 2^p in fixed point.
func atanInv(x int64, p uint) *big.Int {
	term := new(big.Int).Lsh(big.NewInt(1), p)
	term.Quo(term, big.NewInt(x))
	sum := new(big.Int).Set(term)
	x2 := big.NewInt(x * x)
	t := new(big.Int)
	for k := int64(1); ; k++ {
		term.Quo(term, x2)
		if term.Sign() == 0 {
			return sum
		}
		t.Quo(term, big.NewInt(2*k+1))
		if k&1 != 0 {
			sum.Sub(sum, t)
		} else {
			sum.Add(sum, t)
		}
	}
}

func main() {
	bitsNeeded := uint(64 * words)
	p := bitsNeeded + 64 // guard bits
	// Machin: pi = 16*atan(1/5) - 4*atan(1/239)
	pi := new(big.Int).Lsh(atanInv(5, p), 4)
	pi.Sub(pi, new(big.Int).Lsh(atanInv(239, p), 2))
	// floor(2/pi * 2^bitsNeeded) = 2^(bitsNeeded+p+1) / (pi * 2^p)
	t := new(big.Int).Lsh(big.NewInt(1), bitsNeeded+p+1)
	t.Quo(t, pi)

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by internal/gentables; DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package float")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// twoOverPi holds the fraction bits of 2/pi, most significant word first:")
	fmt.Fprintln(&b, "// 2/pi = sum of twoOverPi[i] * 2^(-64*(i+1)).")
	fmt.Fprintf(&b, "var twoOverPi = [%d]uint64{\n", words)
	mask := new(big.Int).SetUint64(^uint64(0))
	for i := range words {
		w := new(big.Int).Rsh(t, uint(64*(words-1-i)))
		fmt.Fprintf(&b, "0x%016X,", w.And(w, mask).Uint64())
		if i%4 == 3 {
			fmt.Fprintln(&b)
		}
	}
	fmt.Fprintln(&b, "}")
	src, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("trig_tables.go", src, 0o644); err != nil {
		panic(err)
	}
}
